name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: XO-game
      run: ./XO-game.cpp
    - name: XOboard
      run: ./XOboard.cpp
    - name: run
      run: ./XOboard.h